name: Publish clash-transparent-redir-proxy-docker
on:
  schedule:
    - cron: 0 21 * * *
  workflow_dispatch:
    inputs:
      tags: 
         description: 'Run Tags'
  push:
    branches:
      - master
    tags:
      - '*'
    paths-ignore:
      - config.yaml
      - docker-compose.yml
      - README.md
      - LICENSE
      - Dockerfile
      - Dockerfile3
jobs:
  build:
    name: build_docker_image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile2
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/clash-transparent-redir-proxy-docker:latest
      - 
        name: 删除工作流
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 3
